### ISSUE TITLE
Search Issue on Windows 8.1 /Chrome

### ISSUE THREAD

**Issue by smallcapyo** [SkinyMonkey/sound-nuggets#26]
Wrong Link.
Klicking any Search Result leads to the "Add Track to" Option instead of "Play that Track".

Bug or Feature?

thx.

**Comment by SkinyMonkey** [comment]
It's a feature, i never personnaly rely on the search bar on the top to play a track directly.

What I can do is add a way to play the track from the "Add track" modal that appears.

**Comment by smallcapyo** [comment]
OK☺️
